//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artefacts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artefacts()
        {
            this.UserAttitude = new HashSet<UserAttitude>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public System.DateTime PublisheTime { get; set; }
        public string ArtefactImage { get; set; }
        public int LikeNum { get; set; }
        public int ArtefactTypeID { get; set; }
        public int NowState { get; set; }
    
        public virtual ArtefactType ArtefactType { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAttitude> UserAttitude { get; set; }
    }
}
