//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
            this.ProductReviews = new HashSet<ProductReviews>();
            this.ShoppingCar = new HashSet<ShoppingCar>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string GoodsImage { get; set; }
        public decimal RMBPrice { get; set; }
        public int CreditPrice { get; set; }
        public int Stock { get; set; }
        public string UserName { get; set; }
        public int GoodsTypeID { get; set; }
    
        public virtual GoodsType GoodsType { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReviews> ProductReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCar> ShoppingCar { get; set; }
    }
}
