//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Junks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Junks()
        {
            this.GarbagerAttitude = new HashSet<GarbagerAttitude>();
        }
    
        public int ID { get; set; }
        public string JunksName { get; set; }
        public string JunkImage { get; set; }
        public int JunkTypeId { get; set; }
        public string UserName { get; set; }
        public int LikeNum { get; set; }
        public int DislikeNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GarbagerAttitude> GarbagerAttitude { get; set; }
        public virtual JunkType JunkType { get; set; }
        public virtual Users Users { get; set; }
    }
}
