//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public string UserName { get; set; }
        public int FromPost { get; set; }
        public int ReplyFloor { get; set; }
        public int FloorNumber { get; set; }
        public System.DateTime SendTime { get; set; }
        public int NowState { get; set; }
        public int IsReaded { get; set; }
    
        public virtual Posts Posts { get; set; }
        public virtual Users Users { get; set; }
    }
}
