//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string UserName { get; set; }
        public string NickName { get; set; }
        public string Gender { get; set; }
        public string UserEmail { get; set; }
        public string PhoneNumber { get; set; }
        public string UserImage { get; set; }
        public string UserDesc { get; set; }
        public int UserCredit { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public int NewsPower { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
